# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: the-noises 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "the-noises"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["ninoseki"]
  s.date = "2014-04-01"
  s.description = "\u{30b6}\u{30fb}\u{30ce}\u{30a4}\u{30b8}\u{30fc}\u{30ba}\u{306e}\u{30dd}\u{30c3}\u{30c9}\u{30ad}\u{30e3}\u{30b9}\u{30c8}\u{7528}Ruby\u{30af}\u{30e9}\u{30a4}\u{30a2}\u{30f3}\u{30c8}"
  s.email = "zgok0079@gmail.com"
  s.executables = ["the-noises"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/the-noises",
    "lib/the-noises.rb",
    "spec/spec_helper.rb",
    "spec/the-noises_spec.rb",
    "the-noises.gemspec"
  ]
  s.homepage = "http://github.com/ninoseki/ruby-the-noises"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "\u{30b6}\u{30fb}\u{30ce}\u{30a4}\u{30b8}\u{30fc}\u{30ba}\u{306e}\u{30dd}\u{30c3}\u{30c9}\u{30ad}\u{30e3}\u{30b9}\u{30c8}\u{7528}Ruby\u{30af}\u{30e9}\u{30a4}\u{30a2}\u{30f3}\u{30c8}"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.19.1"])
      s.add_runtime_dependency(%q<ruby-progressbar>, ["~> 1.4.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<capture-output>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<thor>, ["~> 0.19.1"])
      s.add_dependency(%q<ruby-progressbar>, ["~> 1.4.2"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<capture-output>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.19.1"])
    s.add_dependency(%q<ruby-progressbar>, ["~> 1.4.2"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<capture-output>, ["~> 1.0.0"])
  end
end

